# Generated by Django 2.2 on 2019-05-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='your_name',
            new_name='name',
        ),
    ]
